name: Add to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.1.0
        with:
          project: engineering-technology
          column: To do
          repo-token: ${{ secrets.GITHUB_PERSONAL_ORG }}
