name: Add Project
on:
  issues:
    types: [opened]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: dsciztech/graphql-action
        id: add_project
        with:
          query: |
            mutation release($node_id:String!) {
              addProjectCard(
                input: {
                  contentId: $node_id,
                  projectColumnId: "MDEzOlByb2plY3RDb2x1bW43MTQ2NTA3"
                }
              ) {
                clientMutationId
              }
            }
          node_id: ${{ github.event.issue.node_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PERSONAL_ORG }}
