name: Add Project
on:
  issues:
    types: [opened]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: dsciztech/graphql-action@0.1
        id: add_project
        with:
          query: |
            mutation
          node_id: ${{ github.event.issue.node_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PERSONAL_ORG }}
