name: Add Project
on:
  issues:
    types: [opened]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: add_project
        with:
          query: |
            mutation {
              addProjectCard(
                input: {
                  contentId: $node,
                  projectColumnId: "MDEzOlByb2plY3RDb2x1bW43MTQ2NTA3"
                }
              ) {
                clientMutationId
              }
            }
          node: ${{ github.event.issue.node_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
